pipes:
    actions:
        profile_updated: ~
        profile_anniversary: ~
        profile_new_friends
            triggering_events: [profile_new_connection, profile_friends_new_connection, profile_new_school, profile_school_new_student]

    stores:
        # This store updates the projection containing profile network : friends, friends of friends and school friends
        profile_network:
            service: wizbii.pipeline.stores.profile.network
            triggering_actions: [profile_new_friends]

        # This store updates the projection containing profile thanxers
        profile_thanx:
            service: wizbii.pipeline.stores.profile.network
            triggering_actions: [profile_update_thanx]

        # This store updates the projection containing profile identity card : first_name, last_name, title, age, network
        # and thanx counters
        profile_identity_card:
            service: wizbii.pipeline.stores.profile.identity_card
            triggering_actions: [profile_updated, profile_anniversary]
            triggering_stores: [profile_network, profile_thanx]

        # This store updates the projection containing profile identity card : first_name, last_name, title, age, network
        # and thanx counters
        profile_proxy:
            service: wizbii.pipeline.stores.profile.profile_proxy
            triggering_actions: [profile_updated, profile_anniversary]
            triggering_stores: [profile_network, profile_thanx]

        # This store updates the projection containing profile identity card : first_name, last_name, title, age, network
        # and thanx counters
        profile_stats:
            service: wizbii.pipeline.stores.profile.profile_stats
            triggering_actions: [profile_updated, profile_anniversary]
            triggering_stores: [profile_network, profile_thanx]

        # This store updates the projection containing profile identity card : first_name, last_name, title, age, network
        # and thanx counters
        profile_search:
            service: wizbii.pipeline.stores.profile.profile_search
            triggering_actions: [profile_updated, profile_anniversary]
            triggering_stores: [profile_network, profile_thanx]