language: php

php:
  - 5.6
  - 7.0

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: ./vendor/phpunit/phpunit/phpunit

notifications:
  slack: wizbii:8bhSf4D5IDXCDCN906umk9Jr